version: 0.2 
 
phases: 
  install: 
    runtime-versions:
      java: corretto8
    commands: 
      # - echo Nothing to do in the install phase... 
  pre_build: 
    commands: 
      # - echo Nothing to do in the pre_build phase... 
      - gradle -v
      - java -version
  build: 
    commands: 
      # - echo Build started on `date` 
      # - mvn install 
      - ./gradlew build
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - mv scripts build/libs 
artifacts: 
  files: 
     - build/libs/**/*
     - appspec.yml 